format: 0.1.0
name: simple-storage
validation: "./validator.cue"
jobs:
  sanity:
    steps:
    - uri: fs/build
      method: setData
      args:
        address: "0x5fbdb2315678afecb367f032d93f642f64180aa3"
        value: 100
    - uri: fs/build
      method: getData
      args:
        address: "0x5fbdb2315678afecb367f032d93f642f64180aa3"
